backend:
  name: git-gateway
  branch: master

# when using the default proxy server port
local_backend: true

media_library:
  name: cloudinary
  config:
    cloud_name: sorthvid
    api_key: 675546469724492

media_folder: static/img
public_folder: /img

collections:
  - name: "collectionStyles"
    label: "Collection item"
    folder: "assets/content/collectionStyles"
    create: true
    format: "json"
    slug: "{{year}}-{{month}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Style #", name: "styleid", widget: "string", hint: "Unique identifier ex. 'F34897'" }
      - { label: "Name", name: "name", widget: "string", hint: "Product name ex. 'Pleated georgette'" }
      - { label: "Program", name: "program", widget: "string", hint: "ID of program ex. '1972'" }
      - label: "Filters"
        name: "filters"
        widget: "relation"
        multiple: true
        collection: "filters"
        searchFields: ["id", "name"]
        valueField: "id"
        hint: "List of filters, the style will appear under"
      - { label: "Program Display name", name: "programName", widget: "string", hint: "Display name of program ex. 'Stripe cotton'" }
      - { label: "Material", name: "material", widget: "string", hint: "Name of material" }
      - { label: "Drop", name: "drop", widget: "string", hint: "Label for drop ex. 'November'" }
      - { label: "Color names", name: "colorNames", widget: "string", hint: "Names of colors available ex. 'Brunnera Blue, Sunflower Yellow'" }
      - { label: "Color Id", name: "colorId", widget: "string", hint: "ID of color" }
      - label: "Wholesale Price"
        name: "wholeSalePrice"
        widget: "list"
        hint: "Wholesale prices with currency"
        fields:
          - { label: Price, name: price, widget: string }
          - {
              label: Currency,
              name: currency,
              widget: select,
              options: ["DKK", "EUR", "USD"],
            }
      - label: "Retailer Price"
        name: "retailerPrice"
        widget: "list"
        hint: "Retail prices with currency"
        fields:
          - { label: Price, name: price, widget: string }
          - {
              label: Currency,
              name: currency,
              widget: select,
              options: ["DKK", "EUR", "USD"],
            }
      - { label: "Description", name: "description", widget: "markdown", hint: "Long description of style" }  
  - name: "collectionFilters"
    label: "Collection filter"
    folder: "assets/content/collectionFilters"
    create: true
    format: "json"
    slug: "{{year}}-{{month}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Unique identifier",
          name: "id",
          widget: "string",
          hint: "ex. 'c1'"
        }
      - { 
          label: "Display name", 
          name: "name", 
          widget: "string",
          hint: "ex. 'Animal print'"
        }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          min: 0,
          max: 100,
          default: 0,
          hint: "Optional ordering position"
        }
  - name: "mediaAssets"
    label: "Media asset"
    folder: "assets/content/mediaAssets"
    create: true
    format: "json"
    slug: "{{year}}-{{month}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Style #",
          name: "styleId",
          widget: "relation",
          multiple: true,
          collection: "style",
          searchFields: ["styleid", "name"],
          valueField: "styleid",
          displayFields: ["styleid", "name"],
          hint: "Reference to unique style ID"
        }
      - { label: "Asset title", name: "name", widget: "string", hint: "Title for image window ex. 'pleated_georgette_1.jpg'" }
      - label: "image"
        name: "Cloudinary media reference"
        widget: "image"
      - label: "Media type"
        name: "type"
        widget: "select"
        multiple: false
        options: ["video", "image"]
        hint: "Either image or video"
      - {
          label: "Aspects",
          name: "Aspects",
          widget: "select",
          options: ["landscape", "portrait", "square"],
          default: "portrait",
          hint: "Aspect of media"
        }
      - { label: "Visible", name: "visible", widget: "boolean", default: true, hint: "If false, the asset can only be seen when clicking 'Optional assets' in Desktop Assistant" }
      - { label: "On top", name: "onTop", widget: "boolean", default: false, hint: "If true, the asset will be used for Collection overview list thumbnail. NOTE: Try to only set 1 asset on top pr. style" }
