backend:
  name: git-gateway
  branch: master

# when using the default proxy server port
local_backend: true

media_library:
  name: cloudinary
  config:
    cloud_name: sorthvid
    api_key: 675546469724492

media_folder: static/img
public_folder: /img

collections:
  - name: "style"
    label: "Style"
    folder: "assets/content/style"
    create: true
    format: "json"
    slug: "{{year}}-{{month}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Styleid", name: "styleid", widget: "string", hint: "S-12343" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Program", name: "program", widget: "string" }
      - label: "Collections (belongs to)"
        name: "collection"
        widget: "relation"
        multiple: true
        collection: "collection"
        searchFields: ["id", "name"]
        valueField: "id"
      - {
          label: "Products",
          name: "products",
          widget: "relation",
          multiple: true,
          collection: "product",
          searchFields: ["sku", "name"],
          valueField: "sku",
          displayFields: ["sku", "name"],
        }
      - { label: "Program Display name", name: "programName", widget: "string" }
      - { label: "Material", name: "material", widget: "string" }
      - { label: "Drop", name: "drop", widget: "string" }
      - { label: "Color names", name: "colorNames", widget: "string" }
      - { label: "Color Id", name: "colorId", widget: "string" }
      - label: "Wholesale Price"
        name: "wholeSalePrice"
        widget: "list"
        fields:
          - { label: Price, name: price, widget: string }
          - {
              label: Currency,
              name: currency,
              widget: select,
              options: ["DKK", "EUR", "USD"],
            }
      - label: "Retailer Price"
        name: "retailerPrice"
        widget: "list"
        fields:
          - { label: Price, name: price, widget: string }
          - {
              label: Currency,
              name: currency,
              widget: select,
              options: ["DKK", "EUR", "USD"],
            }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: "product"
    label: "Product (asset)"
    folder: "assets/content/product"
    create: true
    format: "json"
    slug: "{{year}}-{{month}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "SKU", name: "sku", widget: "string", hint: "GHF-1243232" }
      - { label: "Prdoduct name", name: "name", widget: "string" }
      - label: "image"
        name: "image"
        widget: "image"
      - label: "Media type"
        name: "type"
        widget: "select"
        multiple: false
        options: ["video", "image"]
      - { label: "Visible", name: "visible", widget: "boolean", default: true }
      - { label: "On Top", name: "onTop", widget: "boolean" }
  - name: "collection"
    label: "Cellections"
    folder: "assets/content/collection"
    create: true
    format: "json"
    slug: "{{year}}-{{month}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Unique Identityer",
          name: "id",
          widget: "string",
          hint: "dresses",
        }
      - { label: "Display name", name: "name", widget: "string" }
