<template>
	<div>
		<div class="assistant__content">
			<div class="assistant__text" v-if="content">
				<h3 v-if="content.headline">{{ content.headline }}</h3>
				<p v-if="content.bodyText" v-html="content.bodyText"></p>
			</div>
		</div>
	</div>
</template>

<script>
import { mapState } from 'vuex'
export default {
	name: 'assistant-mode-custom',
	computed: {
		...mapState(['topMostWindow']),
		...mapState('assistant', ['texts', 'customText']),
		autogeneratedContent() {
			// if the cms has a file with itemId that matches the current windowContent.contentId,
			// then show that text!
			return this.texts[this.topMostWindow.contentId]
				? this.texts[this.topMostWindow.contentId]
				: null
		},
		content() {
			if (this.autogeneratedContent) {
				return this.autogeneratedContent
			}
			// windowContent.assistant.text can either be a string which corresponds to a CMS assistant/itemId,
			// or defined on the code as { headline: 'foo', bodyText: 'bar }
			return typeof this.customText === 'string'
				? this.$store.state.assistant.texts[this.customText]
				: this.customText
		}
	}
}
</script>