name: Test CMS files

on:
  push:
    branches: [releases/2021-feb]
  pull_request:
    branches: [releases/2021-feb]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.9]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test

      - name: Tests ✅
        if: ${{ success() }}
        run: |
          curl --request POST           --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'           --header 'content-type: application/json'           --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      # - name: Tests 🚨
      #   if: ${{ failure() }}
      #   run: |
      #     curl --request POST           --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'           --header 'content-type: application/json'           --data '{
      #       "context": "tests",
      #       "state": "failure",
      #       "description": "Tests failed",
      #       "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      #     }'
